'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace DUO_VOAanlevering_InschrijvingVO_V1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(Name:="DUO_VOAanlevering_InschrijvingVO_V1.0_PortType", [Namespace]:="http://duo.nl/contract/DUO_VOAanlevering_InschrijvingVO_V1", ConfigurationName:="DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType"& _ 
        "")>  _
    Public Interface DUO_VOAanlevering_InschrijvingVO_V10_PortType
        
        'CODEGEN: Generating message contract since the operation aanleverenInschrijvingVO is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://duo.nl/contract/DUO_VOAanlevering_InschrijvingVO_V1/aanleverenInschrijving"& _ 
            "VO", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(InschrijvingPeriode)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Bedrijfsdocument))>  _
        Function aanleverenInschrijvingVO(ByVal request As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVORequest) As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVOResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://duo.nl/contract/DUO_VOAanlevering_InschrijvingVO_V1/aanleverenInschrijving"& _ 
            "VO", ReplyAction:="*")>  _
        Function aanleverenInschrijvingVOAsync(ByVal request As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVORequest) As System.Threading.Tasks.Task(Of DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVOResponse)
        
        'CODEGEN: Generating message contract since the operation aanleverenVerwijderingInschrijvingVO is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://duo.nl/contract/DUO_VOAanlevering_InschrijvingVO_V1/aanleverenVerwijdering"& _ 
            "InschrijvingVO", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(InschrijvingPeriode)),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Bedrijfsdocument))>  _
        Function aanleverenVerwijderingInschrijvingVO(ByVal request As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVORequest) As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVOResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://duo.nl/contract/DUO_VOAanlevering_InschrijvingVO_V1/aanleverenVerwijdering"& _ 
            "InschrijvingVO", ReplyAction:="*")>  _
        Function aanleverenVerwijderingInschrijvingVOAsync(ByVal request As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVORequest) As System.Threading.Tasks.Task(Of DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVOResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1")>  _
    Partial Public Class AanleverenInschrijvingVO_Request
        Inherits InschrijvingVO
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(AanleverenInschrijvingVO_Request)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1")>  _
    Partial Public Class InschrijvingVO
        Inherits Inschrijving
        
        Private inschrijvingPeriodeVOField() As InschrijvingPeriodeVO
        
        Private ontwikkelingsperspectiefField() As Ontwikkelingsperspectief
        
        Private verblijfAndereInstellingField() As VerblijfAndereInstelling
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("inschrijvingPeriodeVO", Order:=0)>  _
        Public Property inschrijvingPeriodeVO() As InschrijvingPeriodeVO()
            Get
                Return Me.inschrijvingPeriodeVOField
            End Get
            Set
                Me.inschrijvingPeriodeVOField = value
                Me.RaisePropertyChanged("inschrijvingPeriodeVO")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("ontwikkelingsperspectief", Order:=1)>  _
        Public Property ontwikkelingsperspectief() As Ontwikkelingsperspectief()
            Get
                Return Me.ontwikkelingsperspectiefField
            End Get
            Set
                Me.ontwikkelingsperspectiefField = value
                Me.RaisePropertyChanged("ontwikkelingsperspectief")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("verblijfAndereInstelling", Order:=2)>  _
        Public Property verblijfAndereInstelling() As VerblijfAndereInstelling()
            Get
                Return Me.verblijfAndereInstellingField
            End Get
            Set
                Me.verblijfAndereInstellingField = value
                Me.RaisePropertyChanged("verblijfAndereInstelling")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1")>  _
    Partial Public Class InschrijvingPeriodeVO
        Inherits InschrijvingPeriode
        
        Private vestigingField As String
        
        Private leerjaarField As String
        
        Private indicatieBekostigbaarField As Boolean
        
        Private experimentField() As Experiment
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property vestiging() As String
            Get
                Return Me.vestigingField
            End Get
            Set
                Me.vestigingField = value
                Me.RaisePropertyChanged("vestiging")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property leerjaar() As String
            Get
                Return Me.leerjaarField
            End Get
            Set
                Me.leerjaarField = value
                Me.RaisePropertyChanged("leerjaar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property indicatieBekostigbaar() As Boolean
            Get
                Return Me.indicatieBekostigbaarField
            End Get
            Set
                Me.indicatieBekostigbaarField = value
                Me.RaisePropertyChanged("indicatieBekostigbaar")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("experiment", Order:=3)>  _
        Public Property experiment() As Experiment()
            Get
                Return Me.experimentField
            End Get
            Set
                Me.experimentField = value
                Me.RaisePropertyChanged("experiment")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1")>  _
    Partial Public Class Experiment
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private naamField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=0)>  _
        Public Property naam() As String
            Get
                Return Me.naamField
            End Get
            Set
                Me.naamField = value
                Me.RaisePropertyChanged("naam")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1")>  _
    Partial Public Class VerblijfAndereInstelling
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private datumBeginField As Date
        
        Private datumEindField As Date
        
        Private datumEindFieldSpecified As Boolean
        
        Private brinField As String
        
        Private vestigingField As String
        
        Private verblijfsoortField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=0)>  _
        Public Property datumBegin() As Date
            Get
                Return Me.datumBeginField
            End Get
            Set
                Me.datumBeginField = value
                Me.RaisePropertyChanged("datumBegin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=1)>  _
        Public Property datumEind() As Date
            Get
                Return Me.datumEindField
            End Get
            Set
                Me.datumEindField = value
                Me.RaisePropertyChanged("datumEind")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property datumEindSpecified() As Boolean
            Get
                Return Me.datumEindFieldSpecified
            End Get
            Set
                Me.datumEindFieldSpecified = value
                Me.RaisePropertyChanged("datumEindSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property brin() As String
            Get
                Return Me.brinField
            End Get
            Set
                Me.brinField = value
                Me.RaisePropertyChanged("brin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property vestiging() As String
            Get
                Return Me.vestigingField
            End Get
            Set
                Me.vestigingField = value
                Me.RaisePropertyChanged("vestiging")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=4)>  _
        Public Property verblijfsoort() As String
            Get
                Return Me.verblijfsoortField
            End Get
            Set
                Me.verblijfsoortField = value
                Me.RaisePropertyChanged("verblijfsoort")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1")>  _
    Partial Public Class Ontwikkelingsperspectief
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private datumBeginField As Date
        
        Private datumEindField As Date
        
        Private datumEindFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=0)>  _
        Public Property datumBegin() As Date
            Get
                Return Me.datumBeginField
            End Get
            Set
                Me.datumBeginField = value
                Me.RaisePropertyChanged("datumBegin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=1)>  _
        Public Property datumEind() As Date
            Get
                Return Me.datumEindField
            End Get
            Set
                Me.datumEindField = value
                Me.RaisePropertyChanged("datumEind")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property datumEindSpecified() As Boolean
            Get
                Return Me.datumEindFieldSpecified
            End Get
            Set
                Me.datumEindFieldSpecified = value
                Me.RaisePropertyChanged("datumEindSpecified")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Inschrijving_V1")>  _
    Partial Public Class AanvullendeOpleiding
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private opleidingcodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property opleidingcode() As String
            Get
                Return Me.opleidingcodeField
            End Get
            Set
                Me.opleidingcodeField = value
                Me.RaisePropertyChanged("opleidingcode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(InschrijvingPeriodeVO)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Inschrijving_V1")>  _
    Partial Public Class InschrijvingPeriode
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private datumBeginField As Date
        
        Private onderwijsaanbiederField As String
        
        Private onderwijslocatieField As String
        
        Private opleidingcodeField As String
        
        Private aanvullendeOpleidingField() As AanvullendeOpleiding
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=0)>  _
        Public Property datumBegin() As Date
            Get
                Return Me.datumBeginField
            End Get
            Set
                Me.datumBeginField = value
                Me.RaisePropertyChanged("datumBegin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property onderwijsaanbieder() As String
            Get
                Return Me.onderwijsaanbiederField
            End Get
            Set
                Me.onderwijsaanbiederField = value
                Me.RaisePropertyChanged("onderwijsaanbieder")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property onderwijslocatie() As String
            Get
                Return Me.onderwijslocatieField
            End Get
            Set
                Me.onderwijslocatieField = value
                Me.RaisePropertyChanged("onderwijslocatie")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property opleidingcode() As String
            Get
                Return Me.opleidingcodeField
            End Get
            Set
                Me.opleidingcodeField = value
                Me.RaisePropertyChanged("opleidingcode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("aanvullendeOpleiding", Order:=4)>  _
        Public Property aanvullendeOpleiding() As AanvullendeOpleiding()
            Get
                Return Me.aanvullendeOpleidingField
            End Get
            Set
                Me.aanvullendeOpleidingField = value
                Me.RaisePropertyChanged("aanvullendeOpleiding")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(VerwijderingInschrijving)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AanleverenVerwijderingInschrijvingVO_Request)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(OntvangstBevestiging)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AanleverenVerwijderingInschrijvingVO_Response)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AanleverenInschrijvingVO_Response)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(Inschrijving)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(InschrijvingVO)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AanleverenInschrijvingVO_Request)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Inschrijving_V1")>  _
    Partial Public Class Bedrijfsdocument
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private identificatiecodeBedrijfsdocumentField As String
        
        Private verzendendeInstantieField As String
        
        Private ontvangendeInstantieField As String
        
        Private datumTijdBedrijfsdocumentField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property identificatiecodeBedrijfsdocument() As String
            Get
                Return Me.identificatiecodeBedrijfsdocumentField
            End Get
            Set
                Me.identificatiecodeBedrijfsdocumentField = value
                Me.RaisePropertyChanged("identificatiecodeBedrijfsdocument")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="normalizedString", Order:=1)>  _
        Public Property verzendendeInstantie() As String
            Get
                Return Me.verzendendeInstantieField
            End Get
            Set
                Me.verzendendeInstantieField = value
                Me.RaisePropertyChanged("verzendendeInstantie")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="normalizedString", Order:=2)>  _
        Public Property ontvangendeInstantie() As String
            Get
                Return Me.ontvangendeInstantieField
            End Get
            Set
                Me.ontvangendeInstantieField = value
                Me.RaisePropertyChanged("ontvangendeInstantie")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property datumTijdBedrijfsdocument() As Date
            Get
                Return Me.datumTijdBedrijfsdocumentField
            End Get
            Set
                Me.datumTijdBedrijfsdocumentField = value
                Me.RaisePropertyChanged("datumTijdBedrijfsdocument")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(AanleverenVerwijderingInschrijvingVO_Request)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Inschrijving_V1")>  _
    Partial Public Class VerwijderingInschrijving
        Inherits Bedrijfsdocument
        
        Private itemField As String
        
        Private itemElementNameField As ItemChoiceType1
        
        Private brinField As String
        
        Private inschrijvingvolgnummerField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("burgerservicenummer", GetType(String), Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("onderwijsnummer", GetType(String), Order:=0),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
                Me.RaisePropertyChanged("Item")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemElementName() As ItemChoiceType1
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = value
                Me.RaisePropertyChanged("ItemElementName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property brin() As String
            Get
                Return Me.brinField
            End Get
            Set
                Me.brinField = value
                Me.RaisePropertyChanged("brin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="normalizedString", Order:=3)>  _
        Public Property inschrijvingvolgnummer() As String
            Get
                Return Me.inschrijvingvolgnummerField
            End Get
            Set
                Me.inschrijvingvolgnummerField = value
                Me.RaisePropertyChanged("inschrijvingvolgnummer")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Inschrijving_V1", IncludeInSchema:=false)>  _
    Public Enum ItemChoiceType1
        
        '''<remarks/>
        burgerservicenummer
        
        '''<remarks/>
        onderwijsnummer
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1")>  _
    Partial Public Class AanleverenVerwijderingInschrijvingVO_Request
        Inherits VerwijderingInschrijving
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(AanleverenVerwijderingInschrijvingVO_Response)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AanleverenInschrijvingVO_Response)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Inschrijving_V1")>  _
    Partial Public Class OntvangstBevestiging
        Inherits Bedrijfsdocument
        
        Private ontvangstBevestigingField As OntvangstBevestigingv01
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ontvangstBevestiging() As OntvangstBevestigingv01
            Get
                Return Me.ontvangstBevestigingField
            End Get
            Set
                Me.ontvangstBevestigingField = value
                Me.RaisePropertyChanged("ontvangstBevestiging")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="OntvangstBevestiging-v01", [Namespace]:="http://duo.nl/schema/NL:OCW:GWB:BASIS")>  _
    Public Enum OntvangstBevestigingv01
        
        '''<remarks/>
        J
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1")>  _
    Partial Public Class AanleverenVerwijderingInschrijvingVO_Response
        Inherits OntvangstBevestiging
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1")>  _
    Partial Public Class AanleverenInschrijvingVO_Response
        Inherits OntvangstBevestiging
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(InschrijvingVO)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(AanleverenInschrijvingVO_Request)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Inschrijving_V1")>  _
    Partial Public Class Inschrijving
        Inherits Bedrijfsdocument
        
        Private itemField As String
        
        Private itemElementNameField As ItemChoiceType
        
        Private brinField As String
        
        Private inschrijvingvolgnummerField As String
        
        Private datumInschrijvingField As Date
        
        Private datumUitschrijvingField As Date
        
        Private datumUitschrijvingFieldSpecified As Boolean
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("burgerservicenummer", GetType(String), Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("onderwijsnummer", GetType(String), Order:=0),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
                Me.RaisePropertyChanged("Item")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = value
                Me.RaisePropertyChanged("ItemElementName")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property brin() As String
            Get
                Return Me.brinField
            End Get
            Set
                Me.brinField = value
                Me.RaisePropertyChanged("brin")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="normalizedString", Order:=3)>  _
        Public Property inschrijvingvolgnummer() As String
            Get
                Return Me.inschrijvingvolgnummerField
            End Get
            Set
                Me.inschrijvingvolgnummerField = value
                Me.RaisePropertyChanged("inschrijvingvolgnummer")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=4)>  _
        Public Property datumInschrijving() As Date
            Get
                Return Me.datumInschrijvingField
            End Get
            Set
                Me.datumInschrijvingField = value
                Me.RaisePropertyChanged("datumInschrijving")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="date", Order:=5)>  _
        Public Property datumUitschrijving() As Date
            Get
                Return Me.datumUitschrijvingField
            End Get
            Set
                Me.datumUitschrijvingField = value
                Me.RaisePropertyChanged("datumUitschrijving")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property datumUitschrijvingSpecified() As Boolean
            Get
                Return Me.datumUitschrijvingFieldSpecified
            End Get
            Set
                Me.datumUitschrijvingFieldSpecified = value
                Me.RaisePropertyChanged("datumUitschrijvingSpecified")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Inschrijving_V1", IncludeInSchema:=false)>  _
    Public Enum ItemChoiceType
        
        '''<remarks/>
        burgerservicenummer
        
        '''<remarks/>
        onderwijsnummer
    End Enum
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aanleverenInschrijvingVORequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1", Order:=0)>  _
        Public aanleverenInschrijvingVO_Request As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenInschrijvingVO_Request
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal aanleverenInschrijvingVO_Request As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenInschrijvingVO_Request)
            MyBase.New
            Me.aanleverenInschrijvingVO_Request = aanleverenInschrijvingVO_Request
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aanleverenInschrijvingVOResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1", Order:=0)>  _
        Public aanleverenInschrijvingVO_Response As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenInschrijvingVO_Response
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal aanleverenInschrijvingVO_Response As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenInschrijvingVO_Response)
            MyBase.New
            Me.aanleverenInschrijvingVO_Response = aanleverenInschrijvingVO_Response
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aanleverenVerwijderingInschrijvingVORequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1", Order:=0)>  _
        Public aanleverenVerwijderingInschrijvingVO_Request As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenVerwijderingInschrijvingVO_Request
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal aanleverenVerwijderingInschrijvingVO_Request As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenVerwijderingInschrijvingVO_Request)
            MyBase.New
            Me.aanleverenVerwijderingInschrijvingVO_Request = aanleverenVerwijderingInschrijvingVO_Request
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aanleverenVerwijderingInschrijvingVOResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://duo.nl/schema/DUO_VOAanlevering_InschrijvingVO_V1", Order:=0)>  _
        Public aanleverenVerwijderingInschrijvingVO_Response As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenVerwijderingInschrijvingVO_Response
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal aanleverenVerwijderingInschrijvingVO_Response As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenVerwijderingInschrijvingVO_Response)
            MyBase.New
            Me.aanleverenVerwijderingInschrijvingVO_Response = aanleverenVerwijderingInschrijvingVO_Response
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DUO_VOAanlevering_InschrijvingVO_V10_PortTypeChannel
        Inherits DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DUO_VOAanlevering_InschrijvingVO_V10_PortTypeClient
        Inherits System.ServiceModel.ClientBase(Of DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType)
        Implements DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DUO_VOAanlevering_InschrijvingVO_V1_DUO_VOAanlevering_InschrijvingVO_V10_PortType_aanleverenInschrijvingVO(ByVal request As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVORequest) As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVOResponse Implements DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType.aanleverenInschrijvingVO
            Return MyBase.Channel.aanleverenInschrijvingVO(request)
        End Function
        
        Public Function aanleverenInschrijvingVO(ByVal aanleverenInschrijvingVO_Request As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenInschrijvingVO_Request) As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenInschrijvingVO_Response
            Dim inValue As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVORequest = New DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVORequest()
            inValue.aanleverenInschrijvingVO_Request = aanleverenInschrijvingVO_Request
            Dim retVal As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVOResponse = CType(Me,DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType).aanleverenInschrijvingVO(inValue)
            Return retVal.aanleverenInschrijvingVO_Response
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DUO_VOAanlevering_InschrijvingVO_V1_DUO_VOAanlevering_InschrijvingVO_V10_PortType_aanleverenInschrijvingVOAsync(ByVal request As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVORequest) As System.Threading.Tasks.Task(Of DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVOResponse) Implements DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType.aanleverenInschrijvingVOAsync
            Return MyBase.Channel.aanleverenInschrijvingVOAsync(request)
        End Function
        
        Public Function aanleverenInschrijvingVOAsync(ByVal aanleverenInschrijvingVO_Request As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenInschrijvingVO_Request) As System.Threading.Tasks.Task(Of DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVOResponse)
            Dim inValue As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVORequest = New DUO_VOAanlevering_InschrijvingVO_V1.aanleverenInschrijvingVORequest()
            inValue.aanleverenInschrijvingVO_Request = aanleverenInschrijvingVO_Request
            Return CType(Me,DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType).aanleverenInschrijvingVOAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DUO_VOAanlevering_InschrijvingVO_V1_DUO_VOAanlevering_InschrijvingVO_V10_PortType_aanleverenVerwijderingInschrijvingVO(ByVal request As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVORequest) As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVOResponse Implements DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType.aanleverenVerwijderingInschrijvingVO
            Return MyBase.Channel.aanleverenVerwijderingInschrijvingVO(request)
        End Function
        
        Public Function aanleverenVerwijderingInschrijvingVO(ByVal aanleverenVerwijderingInschrijvingVO_Request As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenVerwijderingInschrijvingVO_Request) As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenVerwijderingInschrijvingVO_Response
            Dim inValue As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVORequest = New DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVORequest()
            inValue.aanleverenVerwijderingInschrijvingVO_Request = aanleverenVerwijderingInschrijvingVO_Request
            Dim retVal As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVOResponse = CType(Me,DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType).aanleverenVerwijderingInschrijvingVO(inValue)
            Return retVal.aanleverenVerwijderingInschrijvingVO_Response
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function DUO_VOAanlevering_InschrijvingVO_V1_DUO_VOAanlevering_InschrijvingVO_V10_PortType_aanleverenVerwijderingInschrijvingVOAsync(ByVal request As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVORequest) As System.Threading.Tasks.Task(Of DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVOResponse) Implements DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType.aanleverenVerwijderingInschrijvingVOAsync
            Return MyBase.Channel.aanleverenVerwijderingInschrijvingVOAsync(request)
        End Function
        
        Public Function aanleverenVerwijderingInschrijvingVOAsync(ByVal aanleverenVerwijderingInschrijvingVO_Request As DUO_VOAanlevering_InschrijvingVO_V1.AanleverenVerwijderingInschrijvingVO_Request) As System.Threading.Tasks.Task(Of DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVOResponse)
            Dim inValue As DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVORequest = New DUO_VOAanlevering_InschrijvingVO_V1.aanleverenVerwijderingInschrijvingVORequest()
            inValue.aanleverenVerwijderingInschrijvingVO_Request = aanleverenVerwijderingInschrijvingVO_Request
            Return CType(Me,DUO_VOAanlevering_InschrijvingVO_V1.DUO_VOAanlevering_InschrijvingVO_V10_PortType).aanleverenVerwijderingInschrijvingVOAsync(inValue)
        End Function
    End Class
End Namespace
