'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace MHSClient
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(Name:="DUO_VOInformatiediensten_IdentificerenPersoonVO_V1.0_PortType", [Namespace]:="http://duo.nl/contract/DUO_VOInformatiediensten_IdentificerenPersoonVO_V1", ConfigurationName:="MHSClient.DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType")>  _
    Public Interface DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType
        
        'CODEGEN: Generating message contract since the operation aanleverenIdentificerenPersoonVO is neither RPC nor document wrapped.
        <System.ServiceModel.OperationContractAttribute(Action:="http://duo.nl/contract/DUO_VOInformatiediensten_IdentificerenPersoonVO_V1/aanleve"& _ 
            "renIdentificerenPersoonVO", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true),  _
         System.ServiceModel.ServiceKnownTypeAttribute(GetType(Bedrijfsdocument))>  _
        Function aanleverenIdentificerenPersoonVO(ByVal request As MHSClient.aanleverenIdentificerenPersoonVORequest) As MHSClient.aanleverenIdentificerenPersoonVOResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://duo.nl/contract/DUO_VOInformatiediensten_IdentificerenPersoonVO_V1/aanleve"& _ 
            "renIdentificerenPersoonVO", ReplyAction:="*")>  _
        Function aanleverenIdentificerenPersoonVOAsync(ByVal request As MHSClient.aanleverenIdentificerenPersoonVORequest) As System.Threading.Tasks.Task(Of MHSClient.aanleverenIdentificerenPersoonVOResponse)
    End Interface
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOInformatiediensten_IdentificerenPersoonVO_V1")>  _
    Partial Public Class aanleverenIdentificerenPersoonVO_Request
        Inherits Bedrijfsdocument
        
        Private huidigOnderwijsnummerField As String
        
        Private geboorteDatumField As String
        
        Private geslachtField As Geslachtv02
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property huidigOnderwijsnummer() As String
            Get
                Return Me.huidigOnderwijsnummerField
            End Get
            Set
                Me.huidigOnderwijsnummerField = value
                Me.RaisePropertyChanged("huidigOnderwijsnummer")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=1)>  _
        Public Property geboorteDatum() As String
            Get
                Return Me.geboorteDatumField
            End Get
            Set
                Me.geboorteDatumField = value
                Me.RaisePropertyChanged("geboorteDatum")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property geslacht() As Geslachtv02
            Get
                Return Me.geslachtField
            End Get
            Set
                Me.geslachtField = value
                Me.RaisePropertyChanged("geslacht")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("metPGN", GetType(MetPGN), Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute("zonderPGN", GetType(ZonderPGN), Order:=3)>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
                Me.RaisePropertyChanged("Item")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="Geslacht-v02", [Namespace]:="http://duo.nl/schema/NL:OCW:GWB:BASIS")>  _
    Public Enum Geslachtv02
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("1")>  _
        Item1
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("2")>  _
        Item2
        
        '''<remarks/>
        <System.Xml.Serialization.XmlEnumAttribute("3")>  _
        Item3
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Informatiediensten_V1")>  _
    Partial Public Class MetPGN
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private itemField As String
        
        Private itemElementNameField As ItemChoiceType
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("burgerservicenummer", GetType(String), Order:=0),  _
         System.Xml.Serialization.XmlElementAttribute("onderwijsnummer", GetType(String), Order:=0),  _
         System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")>  _
        Public Property Item() As String
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
                Me.RaisePropertyChanged("Item")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1),  _
         System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property ItemElementName() As ItemChoiceType
            Get
                Return Me.itemElementNameField
            End Get
            Set
                Me.itemElementNameField = value
                Me.RaisePropertyChanged("ItemElementName")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Informatiediensten_V1", IncludeInSchema:=false)>  _
    Public Enum ItemChoiceType
        
        '''<remarks/>
        burgerservicenummer
        
        '''<remarks/>
        onderwijsnummer
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Informatiediensten_V1")>  _
    Partial Public Class BinnenlandsAdres
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private straatnaamField As String
        
        Private huisnummerField As String
        
        Private huisletterField As String
        
        Private huisnummerToevoegingField As String
        
        Private huisnummerAanduidingField As HuisnummerAanduidingv02
        
        Private huisnummerAanduidingFieldSpecified As Boolean
        
        Private locatieOmschrijvingField As String
        
        Private postcodeField As String
        
        Private plaatsnaamField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=0)>  _
        Public Property straatnaam() As String
            Get
                Return Me.straatnaamField
            End Get
            Set
                Me.straatnaamField = value
                Me.RaisePropertyChanged("straatnaam")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=1)>  _
        Public Property huisnummer() As String
            Get
                Return Me.huisnummerField
            End Get
            Set
                Me.huisnummerField = value
                Me.RaisePropertyChanged("huisnummer")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=2)>  _
        Public Property huisletter() As String
            Get
                Return Me.huisletterField
            End Get
            Set
                Me.huisletterField = value
                Me.RaisePropertyChanged("huisletter")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property huisnummerToevoeging() As String
            Get
                Return Me.huisnummerToevoegingField
            End Get
            Set
                Me.huisnummerToevoegingField = value
                Me.RaisePropertyChanged("huisnummerToevoeging")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=4)>  _
        Public Property huisnummerAanduiding() As HuisnummerAanduidingv02
            Get
                Return Me.huisnummerAanduidingField
            End Get
            Set
                Me.huisnummerAanduidingField = value
                Me.RaisePropertyChanged("huisnummerAanduiding")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlIgnoreAttribute()>  _
        Public Property huisnummerAanduidingSpecified() As Boolean
            Get
                Return Me.huisnummerAanduidingFieldSpecified
            End Get
            Set
                Me.huisnummerAanduidingFieldSpecified = value
                Me.RaisePropertyChanged("huisnummerAanduidingSpecified")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=5)>  _
        Public Property locatieOmschrijving() As String
            Get
                Return Me.locatieOmschrijvingField
            End Get
            Set
                Me.locatieOmschrijvingField = value
                Me.RaisePropertyChanged("locatieOmschrijving")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=6)>  _
        Public Property postcode() As String
            Get
                Return Me.postcodeField
            End Get
            Set
                Me.postcodeField = value
                Me.RaisePropertyChanged("postcode")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=7)>  _
        Public Property plaatsnaam() As String
            Get
                Return Me.plaatsnaamField
            End Get
            Set
                Me.plaatsnaamField = value
                Me.RaisePropertyChanged("plaatsnaam")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="HuisnummerAanduiding-v02", [Namespace]:="http://duo.nl/schema/NL:OCW:GWB:BASIS")>  _
    Public Enum HuisnummerAanduidingv02
        
        '''<remarks/>
        by
        
        '''<remarks/>
        [to]
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Informatiediensten_V1")>  _
    Partial Public Class BuitenlandsAdres
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private adresregelBuitenland1Field As String
        
        Private adresregelBuitenland2Field As String
        
        Private adresregelBuitenland3Field As String
        
        Private landcodeField As String
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=0)>  _
        Public Property adresregelBuitenland1() As String
            Get
                Return Me.adresregelBuitenland1Field
            End Get
            Set
                Me.adresregelBuitenland1Field = value
                Me.RaisePropertyChanged("adresregelBuitenland1")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=1)>  _
        Public Property adresregelBuitenland2() As String
            Get
                Return Me.adresregelBuitenland2Field
            End Get
            Set
                Me.adresregelBuitenland2Field = value
                Me.RaisePropertyChanged("adresregelBuitenland2")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=2)>  _
        Public Property adresregelBuitenland3() As String
            Get
                Return Me.adresregelBuitenland3Field
            End Get
            Set
                Me.adresregelBuitenland3Field = value
                Me.RaisePropertyChanged("adresregelBuitenland3")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property landcode() As String
            Get
                Return Me.landcodeField
            End Get
            Set
                Me.landcodeField = value
                Me.RaisePropertyChanged("landcode")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Informatiediensten_V1")>  _
    Partial Public Class ZonderPGN
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private achternaamField As String
        
        Private voorvoegselsField As String
        
        Private voornamenField As String
        
        Private itemField As Object
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=0)>  _
        Public Property achternaam() As String
            Get
                Return Me.achternaamField
            End Get
            Set
                Me.achternaamField = value
                Me.RaisePropertyChanged("achternaam")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=1)>  _
        Public Property voorvoegsels() As String
            Get
                Return Me.voorvoegselsField
            End Get
            Set
                Me.voorvoegselsField = value
                Me.RaisePropertyChanged("voorvoegsels")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="token", Order:=2)>  _
        Public Property voornamen() As String
            Get
                Return Me.voornamenField
            End Get
            Set
                Me.voornamenField = value
                Me.RaisePropertyChanged("voornamen")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute("binnenlandsAdres", GetType(BinnenlandsAdres), Order:=3),  _
         System.Xml.Serialization.XmlElementAttribute("buitenlandsAdres", GetType(BuitenlandsAdres), Order:=3)>  _
        Public Property Item() As Object
            Get
                Return Me.itemField
            End Get
            Set
                Me.itemField = value
                Me.RaisePropertyChanged("Item")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(OntvangstBevestiging)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(aanleverenIdentificerenPersoonVO_Response)),  _
     System.Xml.Serialization.XmlIncludeAttribute(GetType(aanleverenIdentificerenPersoonVO_Request)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Informatiediensten_V1")>  _
    Partial Public Class Bedrijfsdocument
        Inherits Object
        Implements System.ComponentModel.INotifyPropertyChanged
        
        Private identificatiecodeBedrijfsdocumentField As String
        
        Private verzendendeInstantieField As String
        
        Private ontvangendeInstantieField As String
        
        Private datumTijdBedrijfsdocumentField As Date
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property identificatiecodeBedrijfsdocument() As String
            Get
                Return Me.identificatiecodeBedrijfsdocumentField
            End Get
            Set
                Me.identificatiecodeBedrijfsdocumentField = value
                Me.RaisePropertyChanged("identificatiecodeBedrijfsdocument")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="normalizedString", Order:=1)>  _
        Public Property verzendendeInstantie() As String
            Get
                Return Me.verzendendeInstantieField
            End Get
            Set
                Me.verzendendeInstantieField = value
                Me.RaisePropertyChanged("verzendendeInstantie")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(DataType:="normalizedString", Order:=2)>  _
        Public Property ontvangendeInstantie() As String
            Get
                Return Me.ontvangendeInstantieField
            End Get
            Set
                Me.ontvangendeInstantieField = value
                Me.RaisePropertyChanged("ontvangendeInstantie")
            End Set
        End Property
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=3)>  _
        Public Property datumTijdBedrijfsdocument() As Date
            Get
                Return Me.datumTijdBedrijfsdocumentField
            End Get
            Set
                Me.datumTijdBedrijfsdocumentField = value
                Me.RaisePropertyChanged("datumTijdBedrijfsdocument")
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    '''<remarks/>
    <System.Xml.Serialization.XmlIncludeAttribute(GetType(aanleverenIdentificerenPersoonVO_Response)),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOBasisschema_Informatiediensten_V1")>  _
    Partial Public Class OntvangstBevestiging
        Inherits Bedrijfsdocument
        
        Private ontvangstBevestigingField As OntvangstBevestigingv01
        
        '''<remarks/>
        <System.Xml.Serialization.XmlElementAttribute(Order:=0)>  _
        Public Property ontvangstBevestiging() As OntvangstBevestigingv01
            Get
                Return Me.ontvangstBevestigingField
            End Get
            Set
                Me.ontvangstBevestigingField = value
                Me.RaisePropertyChanged("ontvangstBevestiging")
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Xml.Serialization.XmlTypeAttribute(TypeName:="OntvangstBevestiging-v01", [Namespace]:="http://duo.nl/schema/NL:OCW:GWB:BASIS")>  _
    Public Enum OntvangstBevestigingv01
        
        '''<remarks/>
        J
    End Enum
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://duo.nl/schema/DUO_VOInformatiediensten_IdentificerenPersoonVO_V1")>  _
    Partial Public Class aanleverenIdentificerenPersoonVO_Response
        Inherits OntvangstBevestiging
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aanleverenIdentificerenPersoonVORequest
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://duo.nl/schema/DUO_VOInformatiediensten_IdentificerenPersoonVO_V1", Order:=0)>  _
        Public aanleverenIdentificerenPersoonVO_Request As MHSClient.aanleverenIdentificerenPersoonVO_Request
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal aanleverenIdentificerenPersoonVO_Request As MHSClient.aanleverenIdentificerenPersoonVO_Request)
            MyBase.New
            Me.aanleverenIdentificerenPersoonVO_Request = aanleverenIdentificerenPersoonVO_Request
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class aanleverenIdentificerenPersoonVOResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute([Namespace]:="http://duo.nl/schema/DUO_VOInformatiediensten_IdentificerenPersoonVO_V1", Order:=0)>  _
        Public aanleverenIdentificerenPersoonVO_Response As MHSClient.aanleverenIdentificerenPersoonVO_Response
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal aanleverenIdentificerenPersoonVO_Response As MHSClient.aanleverenIdentificerenPersoonVO_Response)
            MyBase.New
            Me.aanleverenIdentificerenPersoonVO_Response = aanleverenIdentificerenPersoonVO_Response
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortTypeChannel
        Inherits MHSClient.DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortTypeClient
        Inherits System.ServiceModel.ClientBase(Of MHSClient.DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType)
        Implements MHSClient.DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MHSClient_DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType_aanleverenIdentificerenPersoonVO(ByVal request As MHSClient.aanleverenIdentificerenPersoonVORequest) As MHSClient.aanleverenIdentificerenPersoonVOResponse Implements MHSClient.DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType.aanleverenIdentificerenPersoonVO
            Return MyBase.Channel.aanleverenIdentificerenPersoonVO(request)
        End Function
        
        Public Function aanleverenIdentificerenPersoonVO(ByVal aanleverenIdentificerenPersoonVO_Request As MHSClient.aanleverenIdentificerenPersoonVO_Request) As MHSClient.aanleverenIdentificerenPersoonVO_Response
            Dim inValue As MHSClient.aanleverenIdentificerenPersoonVORequest = New MHSClient.aanleverenIdentificerenPersoonVORequest()
            inValue.aanleverenIdentificerenPersoonVO_Request = aanleverenIdentificerenPersoonVO_Request
            Dim retVal As MHSClient.aanleverenIdentificerenPersoonVOResponse = CType(Me,MHSClient.DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType).aanleverenIdentificerenPersoonVO(inValue)
            Return retVal.aanleverenIdentificerenPersoonVO_Response
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function MHSClient_DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType_aanleverenIdentificerenPersoonVOAsync(ByVal request As MHSClient.aanleverenIdentificerenPersoonVORequest) As System.Threading.Tasks.Task(Of MHSClient.aanleverenIdentificerenPersoonVOResponse) Implements MHSClient.DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType.aanleverenIdentificerenPersoonVOAsync
            Return MyBase.Channel.aanleverenIdentificerenPersoonVOAsync(request)
        End Function
        
        Public Function aanleverenIdentificerenPersoonVOAsync(ByVal aanleverenIdentificerenPersoonVO_Request As MHSClient.aanleverenIdentificerenPersoonVO_Request) As System.Threading.Tasks.Task(Of MHSClient.aanleverenIdentificerenPersoonVOResponse)
            Dim inValue As MHSClient.aanleverenIdentificerenPersoonVORequest = New MHSClient.aanleverenIdentificerenPersoonVORequest()
            inValue.aanleverenIdentificerenPersoonVO_Request = aanleverenIdentificerenPersoonVO_Request
            Return CType(Me,MHSClient.DUO_VOInformatiediensten_IdentificerenPersoonVO_V10_PortType).aanleverenIdentificerenPersoonVOAsync(inValue)
        End Function
    End Class
End Namespace
